server:
  http:
    addr: 0.0.0.0:8082
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9092
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:@tcp(127.0.0.1:3306)/comment?charset=utf8mb4&parseTime=True
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
snowflake:
  start_time: "2024-01-01 00:00:00"
  node_id: 1
